In [ ]:
# Vanguard Digital Experience Analysis

## Day 1: Can We Trust Our Data?

### Purpose

The purpose of Day 1 is to inspect the four raw Vanguard data files and assess their quality before performing any cleaning, KPI calculation, customer journey reconstruction, or statistical testing.

The analysis will examine:

1. Dataset structure
2. Data types
3. Missing values
4. Duplicate records
5. Unique identifiers
6. Experiment assignments
7. Web event structure
8. Potential data quality issues

No records will be removed or modified until the issues have been investigated and an analytical decision has been justified.

In [8]:
import pandas as pd

demo_df = pd.read_csv("data/raw/df_final_demo.txt")

experiment_df = pd.read_csv(
    "data/raw/df_final_experiment_clients (1).txt"
)

web_pt1_df = pd.read_csv(
    "data/raw/df_final_web_data_pt_1.txt"
)

web_pt2_df = pd.read_csv(
    "data/raw/df_final_web_data_pt_2.txt"
)

In [9]:
print("Client Profiles:", demo_df.shape)
print("Experiment Roster:", experiment_df.shape)
print("Web Data Part 1:", web_pt1_df.shape)
print("Web Data Part 2:", web_pt2_df.shape)

Client Profiles: (70609, 9)
Experiment Roster: (70609, 2)
Web Data Part 1: (343141, 5)
Web Data Part 2: (412264, 5)

In [27]:
##client profiles
demo_df.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [11]:
demo_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70609 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70594 non-null  float64
 4   gendr             70595 non-null  str
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), str(1)
memory usage: 4.8 MB

In [12]:
demo_df.isnull().sum()

client_id            0
clnt_tenure_yr      14
clnt_tenure_mnth    14
clnt_age            15
gendr               14
num_accts           14
bal                 14
calls_6_mnth        14
logons_6_mnth       14
dtype: int64

In [13]:
demo_df.duplicated().sum()

np.int64(0)

In [14]:
demo_df["client_id"].duplicated().sum()

np.int64(0)

In [15]:
demo_df.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,7.060900e+04,70595.000000,70595.000000,70594.000000,70595.000000,7.059500e+04,70595.000000,70595.000000
mean,5.004992e+06,12.052950,150.659367,46.442240,2.255528,1.474452e+05,3.382478,5.566740
std,2.877278e+06,6.871819,82.089854,15.591273,0.534997,3.015087e+05,2.236580,2.353286
min,1.690000e+02,2.000000,33.000000,13.500000,1.000000,1.378942e+04,0.000000,1.000000
25%,2.519329e+06,6.000000,82.000000,32.500000,2.000000,3.734683e+04,1.000000,4.000000
50%,5.016978e+06,11.000000,136.000000,47.000000,2.000000,6.333290e+04,3.000000,5.000000
75%,7.483085e+06,16.000000,192.000000,59.000000,2.000000,1.375449e+05,6.000000,7.000000
max,9.999839e+06,62.000000,749.000000,96.000000,8.000000,1.632004e+07,7.000000,9.000000

In [16]:
demo_df["gendr"].value_counts(dropna=False)

gendr
U      24122
M      23724
F      22746
NaN       14
X          3
Name: count, dtype: int64

In [17]:
demo_df.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [18]:
demo_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70609 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70594 non-null  float64
 4   gendr             70595 non-null  str
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), str(1)
memory usage: 4.8 MB

In [19]:
demo_df.isnull().sum()

client_id            0
clnt_tenure_yr      14
clnt_tenure_mnth    14
clnt_age            15
gendr               14
num_accts           14
bal                 14
calls_6_mnth        14
logons_6_mnth       14
dtype: int64

In [20]:
demo_df.duplicated().sum()

np.int64(0)

In [21]:
demo_df["client_id"].duplicated().sum()

np.int64(0)

In [22]:
demo_df.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,7.060900e+04,70595.000000,70595.000000,70594.000000,70595.000000,7.059500e+04,70595.000000,70595.000000
mean,5.004992e+06,12.052950,150.659367,46.442240,2.255528,1.474452e+05,3.382478,5.566740
std,2.877278e+06,6.871819,82.089854,15.591273,0.534997,3.015087e+05,2.236580,2.353286
min,1.690000e+02,2.000000,33.000000,13.500000,1.000000,1.378942e+04,0.000000,1.000000
25%,2.519329e+06,6.000000,82.000000,32.500000,2.000000,3.734683e+04,1.000000,4.000000
50%,5.016978e+06,11.000000,136.000000,47.000000,2.000000,6.333290e+04,3.000000,5.000000
75%,7.483085e+06,16.000000,192.000000,59.000000,2.000000,1.375449e+05,6.000000,7.000000
max,9.999839e+06,62.000000,749.000000,96.000000,8.000000,1.632004e+07,7.000000,9.000000

In [90]:
demo_df["gendr"].value_counts(dropna=False)

gendr
U      24122
M      23724
F      22746
NaN       14
X          3
Name: count, dtype: int64

In [24]:
demo_df[demo_df.isnull().any(axis=1)]

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
4164,7402828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8316,355337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8677,8412164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9583,4666211,8.0,106.0,NaN,F,2.0,42550.55,4.0,7.0
13444,2222915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18066,4876926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,5277910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28432,7616759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35323,8191345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43518,1227228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46076,8611797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47189,5144725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49846,1037867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63701,1618749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66219,6021001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
## How many young clients?
demo_df.sort_values("clnt_age").head(10)

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
70216,5417612,4.0,59.0,13.5,U,2.0,24435.08,7.0,7.0
67700,6250331,4.0,59.0,14.0,U,2.0,19945.35,3.0,3.0
58281,3677152,22.0,273.0,14.0,F,2.0,16989.14,1.0,1.0
51837,4226013,5.0,65.0,14.5,U,3.0,32835.33,5.0,5.0
63598,49451,14.0,178.0,14.5,M,2.0,15487.91,2.0,2.0
69872,64420,5.0,66.0,14.5,U,2.0,18408.77,3.0,3.0
52964,6366070,4.0,57.0,14.5,U,2.0,47145.86,2.0,2.0
60536,1517553,5.0,60.0,14.5,U,2.0,18343.62,5.0,5.0
55898,6269889,4.0,58.0,14.5,U,2.0,20315.11,6.0,6.0
69648,5817398,5.0,68.0,14.5,U,3.0,73762.45,1.0,1.0

In [26]:
### Initial Findings: Client Profiles

#The Client Profiles dataset contains 70,609 clients and 9 variables.

#The `client_id` field contains no missing values and no duplicate client IDs, supporting its use as the unique client identifier. No complete duplicate rows were identified.

#A small number of missing values were identified in the demographic variables. Most variables contain 14 missing values, while `clnt_age` contains 15. The proportion of missing data is very small relative to the total number of clients. No missing records will be removed until the affected clients are investigated.

#Initial descriptive statistics indicate that client balance is strongly right-skewed. The median balance is substantially lower than the mean, and the maximum balance is much larger than the upper quartile. These values will be investigated as potential outliers, but they will not automatically be removed because high balances may represent legitimate Vanguard clients.

#Client age ranges from 13.5 to 96 years. The youngest observations require further investigation before determining whether they represent valid clients or data quality issues.

#Gender contains the categories U, M, F and X, together with a small number of missing values. The supplied metadata does not define U or X, so these categories will be preserved until there is sufficient evidence to justify recoding them.

#At this stage, the Client Profiles dataset appears structurally reliable, but missing values, unusual ages, gender categories and potential numerical outliers require further investigation.

In [28]:
##Experiment Roster
demo_df[demo_df.isnull().any(axis=1)]

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
4164,7402828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8316,355337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8677,8412164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9583,4666211,8.0,106.0,NaN,F,2.0,42550.55,4.0,7.0
13444,2222915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18066,4876926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,5277910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28432,7616759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35323,8191345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43518,1227228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46076,8611797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47189,5144725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49846,1037867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63701,1618749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66219,6021001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
demo_df.sort_values("clnt_age").head(10)

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
70216,5417612,4.0,59.0,13.5,U,2.0,24435.08,7.0,7.0
67700,6250331,4.0,59.0,14.0,U,2.0,19945.35,3.0,3.0
58281,3677152,22.0,273.0,14.0,F,2.0,16989.14,1.0,1.0
51837,4226013,5.0,65.0,14.5,U,3.0,32835.33,5.0,5.0
63598,49451,14.0,178.0,14.5,M,2.0,15487.91,2.0,2.0
69872,64420,5.0,66.0,14.5,U,2.0,18408.77,3.0,3.0
52964,6366070,4.0,57.0,14.5,U,2.0,47145.86,2.0,2.0
60536,1517553,5.0,60.0,14.5,U,2.0,18343.62,5.0,5.0
55898,6269889,4.0,58.0,14.5,U,2.0,20315.11,6.0,6.0
69648,5817398,5.0,68.0,14.5,U,3.0,73762.45,1.0,1.0

In [30]:
#client age < client tenure
age_tenure_issue = demo_df[
    demo_df["clnt_age"] < demo_df["clnt_tenure_yr"]
]

print("Clients with age lower than tenure:", len(age_tenure_issue))

age_tenure_issue.head(10)

Clients with age lower than tenure: 574

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
108,7449147,27.0,330.0,26.5,F,2.0,215247.66,3.0,6.0
970,4955883,29.0,349.0,26.0,F,2.0,37122.69,2.0,5.0
1138,1330615,23.0,285.0,18.5,M,2.0,35553.33,3.0,6.0
1194,4286237,21.0,257.0,17.5,F,2.0,32577.78,5.0,8.0
1286,1225744,26.0,321.0,25.5,F,2.0,35739.29,0.0,3.0
1840,6435592,23.0,285.0,20.5,F,2.0,33384.66,4.0,7.0
2100,7043670,28.0,343.0,22.5,F,3.0,69571.10,1.0,4.0
2283,5269888,20.0,243.0,17.5,F,2.0,39631.34,6.0,9.0
2291,4230904,23.0,280.0,22.5,M,2.0,54602.13,0.0,3.0
2394,9623027,21.0,262.0,19.0,F,2.0,34105.32,4.0,8.0

In [31]:
under_18 = demo_df[demo_df["clnt_age"] < 18]

print("Clients under 18:", len(under_18))

under_18["clnt_age"].describe()

Clients under 18: 374

count    374.000000
mean      16.525401
std        0.965919
min       13.500000
25%       16.000000
50%       16.500000
75%       17.500000
max       17.500000
Name: clnt_age, dtype: float64

In [32]:
### Missing Data Investigation

#The missing values are concentrated in 15 client records.

#Fourteen clients contain only `client_id`, with all remaining profile variables missing. One additional client contains demographic and account information but has a missing value for `clnt_age`.

#This represents approximately 0.02% of the Client Profiles dataset. No records have been removed at this stage. The experiment assignment of these clients should be checked before deciding how they should be handled in subsequent analysis.

### Age Investigation

#The minimum client age of 13.5 is not an isolated observation. Several clients are between approximately 13.5 and 14.5 years old.

#Some young clients also have relatively long recorded tenure. For example, one 14-year-old client has a recorded tenure of 22 years. This suggests a possible inconsistency between age and tenure for some records.

#These observations will not be removed automatically. Additional logical consistency checks are required to determine the frequency and potential impact of these cases.

In [33]:
age_tenure_issue = demo_df[
    demo_df["clnt_age"] < demo_df["clnt_tenure_yr"]
]

print("Clients with age lower than tenure:", len(age_tenure_issue))

age_tenure_issue.head(10)

Clients with age lower than tenure: 574

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
108,7449147,27.0,330.0,26.5,F,2.0,215247.66,3.0,6.0
970,4955883,29.0,349.0,26.0,F,2.0,37122.69,2.0,5.0
1138,1330615,23.0,285.0,18.5,M,2.0,35553.33,3.0,6.0
1194,4286237,21.0,257.0,17.5,F,2.0,32577.78,5.0,8.0
1286,1225744,26.0,321.0,25.5,F,2.0,35739.29,0.0,3.0
1840,6435592,23.0,285.0,20.5,F,2.0,33384.66,4.0,7.0
2100,7043670,28.0,343.0,22.5,F,3.0,69571.10,1.0,4.0
2283,5269888,20.0,243.0,17.5,F,2.0,39631.34,6.0,9.0
2291,4230904,23.0,280.0,22.5,M,2.0,54602.13,0.0,3.0
2394,9623027,21.0,262.0,19.0,F,2.0,34105.32,4.0,8.0

In [34]:
under_18 = demo_df[demo_df["clnt_age"] < 18]

print("Clients under 18:", len(under_18))

under_18["clnt_age"].describe()

Clients under 18: 374

count    374.000000
mean      16.525401
std        0.965919
min       13.500000
25%       16.000000
50%       16.500000
75%       17.500000
max       17.500000
Name: clnt_age, dtype: float64

In [35]:
print("Clients with age lower than tenure:", len(age_tenure_issue))

Clients with age lower than tenure: 574

In [37]:
### Age and Tenure Consistency

#The dataset contains 374 clients under 18 years old, representing approximately 0.53% of all client profiles. Their recorded ages range from 13.5 to 17.5 years.

#A logical consistency check also identified clients whose recorded tenure in years exceeds their recorded age. Examples include clients with an age of 26 and a tenure of 29 years, and an age of 17.5 with a tenure of 21 years.

#These records may indicate inconsistencies between the age and tenure variables. However, the supplied metadata does not provide enough information to determine the cause.

#No records will be removed or corrected at this stage. The issue will be documented and its relevance to the experimental analysis will be evaluated before making a cleaning decision.

In [38]:
Q1 = demo_df["bal"].quantile(0.25)
Q3 = demo_df["bal"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Q1: 37346.835
Q3: 137544.905
IQR: 100198.07
Lower bound: -112950.27000000002
Upper bound: 287842.01

In [39]:
balance_outliers = demo_df[
    (demo_df["bal"] < lower_bound) |
    (demo_df["bal"] > upper_bound)
]

print("Number of balance outliers:", len(balance_outliers))
print(
    "Percentage of balance outliers:",
    round(len(balance_outliers) / demo_df["bal"].notna().sum() * 100, 2),
    "%"
)

Number of balance outliers: 8018
Percentage of balance outliers: 11.36 %

In [40]:
demo_df.nlargest(10, "bal")[
    ["client_id", "clnt_age", "clnt_tenure_yr", "num_accts", "bal"]
]

       client_id  clnt_age  clnt_tenure_yr  num_accts          bal
39367    9286288      62.5            21.0        3.0  16320040.15
63746    8339240      26.5             6.0        2.0  12838418.01
23849    7070097      53.0            11.0        2.0   8986419.77
13318    9440656      63.0             7.0        2.0   8292996.21
2171     2291985      41.0             7.0        2.0   8247729.97
20871    1678193      65.5            24.0        3.0   8137343.24
31811    6762377      41.5            16.0        3.0   8045102.60
14057    3519657      66.5            18.0        6.0   7741994.01
21184     987970      74.5            14.0        3.0   7339443.17
33222     857273      56.5            31.0        5.0   6716305.28

In [41]:
### Balance Outlier Investigation

#The client balance variable shows substantial right skew.

#Using the IQR method, Q1 is approximately $37,346.84 and Q3 is approximately $137,544.91, producing an upper outlier threshold of approximately $287,842.01.

#A total of 8,018 clients, representing 11.36% of clients with available balance data, are classified as statistical outliers using this rule.

#The largest observed balance is approximately $16.32 million, with several clients holding multimillion dollar balances.

#These observations will not be removed automatically. The IQR method identifies statistically unusual values but does not establish that they are data errors. High balances may represent legitimate Vanguard investment clients. Removing all IQR outliers would also exclude more than 11% of clients with available balance information.

#Balance outliers will therefore be retained. Because the distribution is strongly right skewed, both median and mean values should be considered when describing client balances.

In [42]:
print("Clients with age lower than tenure:", len(age_tenure_issue))

Clients with age lower than tenure: 574

In [44]:
###Quality issue
#574 clients, approximately 0.81% of the Client Profiles dataset, have a recorded tenure in years greater than their recorded age. Based on the supplied variable definitions, these records are logically inconsistent. The available data does not establish whether age or tenure is incorrect, so the records will be flagged rather than automatically corrected or removed.

In [47]:
##Experiment Roster.
experiment_df.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [48]:
experiment_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  70609 non-null  int64
 1   Variation  50500 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.1 MB

In [49]:
experiment_df.isnull().sum()

client_id        0
Variation    20109
dtype: int64

In [50]:
experiment_df.duplicated().sum()

np.int64(0)

In [51]:
experiment_df["client_id"].duplicated().sum()

np.int64(0)

In [52]:
experiment_df["Variation"].value_counts(dropna=False)

Variation
Test       26968
Control    23532
NaN        20109
Name: count, dtype: int64

In [53]:
experiment_df["Variation"].value_counts(
    dropna=False,
    normalize=True
) * 100

Variation
Test       38.193431
Control    33.327196
NaN        28.479372
Name: proportion, dtype: float64

In [54]:
experiment_clients = experiment_df["Variation"].notna().sum()

print("Experimental clients:", experiment_clients)

print(
    experiment_df["Variation"]
    .value_counts(normalize=True)
    .mul(100)
)

Experimental clients: 50500
Variation
Test       53.40198
Control    46.59802
Name: proportion, dtype: float64

In [55]:
### Initial Findings: Experiment Roster

#The Experiment Roster contains 70,609 unique clients. No duplicate rows, duplicate client IDs, or missing client IDs were identified.

#A total of 50,500 clients have an experimental assignment. Of these, 26,968 are assigned to the Test group and 23,532 are assigned to the Control group.

#The remaining 20,109 clients have no recorded variation. Based on the project description, these clients should not be automatically treated as data errors. They are not assigned to either the Test or Control condition and therefore should not be included in direct A/B comparisons unless further evidence supports a different treatment.

#The Test and Control groups are not exactly equal in size. Group comparability will therefore be evaluated using client characteristics before interpreting differences in experimental outcomes.

In [56]:
demo_clients = set(demo_df["client_id"])
experiment_clients = set(experiment_df["client_id"])

print(
    "Clients in demo but not experiment:",
    len(demo_clients - experiment_clients)
)

print(
    "Clients in experiment but not demo:",
    len(experiment_clients - demo_clients)
)

Clients in demo but not experiment: 0
Clients in experiment but not demo: 0

In [57]:
### Client ID Alignment

#The Client Profiles and Experiment Roster contain exactly the same 70,609 client IDs.

#No clients were found exclusively in either dataset. This confirms complete client-level alignment between the demographic data and experiment roster and supports using `client_id` to connect these datasets.

In [58]:
###Digital Footprints

In [59]:
print("Part 1 columns:")
print(web_pt1_df.columns.tolist())

print("\nPart 2 columns:")
print(web_pt2_df.columns.tolist())

Part 1 columns:
['client_id', 'visitor_id', 'visit_id', 'process_step', 'date_time']

Part 2 columns:
['client_id', 'visitor_id', 'visit_id', 'process_step', 'date_time']

In [60]:
print(
    "Same columns:",
    web_pt1_df.columns.tolist() == web_pt2_df.columns.tolist()
)

Same columns: True

In [61]:
web_pt1_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 343141 entries, 0 to 343140
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     343141 non-null  int64
 1   visitor_id    343141 non-null  str
 2   visit_id      343141 non-null  str
 3   process_step  343141 non-null  str
 4   date_time     343141 non-null  str
dtypes: int64(1), str(4)
memory usage: 13.1 MB

In [62]:
web_pt2_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 412264 entries, 0 to 412263
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     412264 non-null  int64
 1   visitor_id    412264 non-null  str
 2   visit_id      412264 non-null  str
 3   process_step  412264 non-null  str
 4   date_time     412264 non-null  str
dtypes: int64(1), str(4)
memory usage: 15.7 MB

In [63]:
print("Web Part 1 missing values:")
print(web_pt1_df.isnull().sum())

print("\nWeb Part 2 missing values:")
print(web_pt2_df.isnull().sum())

Web Part 1 missing values:
client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

Web Part 2 missing values:
client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [64]:
print(
    "Part 1 duplicate rows:",
    web_pt1_df.duplicated().sum()
)

print(
    "Part 2 duplicate rows:",
    web_pt2_df.duplicated().sum()
)

Part 1 duplicate rows: 2095
Part 2 duplicate rows: 8669

In [65]:
print("Part 1 process steps:")
print(web_pt1_df["process_step"].value_counts())

print("\nPart 2 process steps:")
print(web_pt2_df["process_step"].value_counts())

Part 1 process steps:
process_step
start      108910
step_1      73432
step_2      61768
step_3      53628
confirm     45403
Name: count, dtype: int64

Part 2 process steps:
process_step
start      135035
step_1      89761
step_2      71294
step_3      58614
confirm     57560
Name: count, dtype: int64

In [66]:
### Initial Findings: Digital Footprints

#The two Digital Footprints files have identical structures. Both contain the five expected variables: `client_id`, `visitor_id`, `visit_id`, `process_step`, and `date_time`.

#No missing values were identified in either file.

#All recorded `process_step` values correspond to the five expected stages of the Vanguard digital process: `start`, `step_1`, `step_2`, `step_3`, and `confirm`.

#Exact duplicate rows were identified in both files. Part 1 contains 2,095 duplicate rows and Part 2 contains 8,669 duplicate rows. These duplicates will not be removed until their characteristics and potential impact on customer journey reconstruction are investigated.

#Because both files have identical columns and compatible data types, they can be combined vertically into a single Digital Footprints dataset.

In [67]:
web_df = pd.concat(
    [web_pt1_df, web_pt2_df],
    ignore_index=True
)

In [68]:
print("Combined web data shape:", web_df.shape)

Combined web data shape: (755405, 5)

In [69]:
print(
    "Combined duplicate rows:",
    web_df.duplicated().sum()
)

Combined duplicate rows: 10764

In [70]:
web_df["date_time"] = pd.to_datetime(
    web_df["date_time"]
)

In [71]:
web_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  str
 2   visit_id      755405 non-null  str
 3   process_step  755405 non-null  str
 4   date_time     755405 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 28.8 MB

In [72]:
### Date and Time Conversion

#The `date_time` variable was initially loaded as text. Because this variable represents the timestamp of each web interaction and will be required to order events chronologically, it was converted to a datetime data type.

#No timestamp values were changed or removed during this conversion.

In [73]:
print("Earliest event:", web_df["date_time"].min())
print("Latest event:", web_df["date_time"].max())

Earliest event: 2017-03-15 00:03:03
Latest event: 2017-06-20 23:59:57

In [75]:
### Combined Digital Footprints Validation

#The two Digital Footprints files were combined vertically after confirming that they contain identical columns and compatible data types.

#The resulting dataset contains 755,405 event records and 5 variables.

#A total of 10,764 exact duplicate rows remain in the combined dataset. This is the same total identified in the two original files, indicating that the combination did not introduce additional duplicate events across the two source files.

#The `date_time` variable was converted from text to a datetime format to support chronological journey reconstruction.

#The observed web activity ranges from March 15, 2017 at 00:03:03 to June 20, 2017 at 23:59:57. This aligns with the A/B test period stated in the project brief.

In [77]:
###Inspect the Identifier Hierarchy
print("Unique clients:", web_df["client_id"].nunique())
print("Unique visitors:", web_df["visitor_id"].nunique())
print("Unique visits:", web_df["visit_id"].nunique())

Unique clients: 120157
Unique visitors: 130236
Unique visits: 158095

In [78]:
visitor_client_counts = (
    web_df.groupby("visitor_id")["client_id"]
    .nunique()
)

print(
    "Visitors linked to more than one client:",
    (visitor_client_counts > 1).sum()
)

Visitors linked to more than one client: 1645

In [79]:
visit_client_counts = (
    web_df.groupby("visit_id")["client_id"]
    .nunique()
)

print(
    "Visits linked to more than one client:",
    (visit_client_counts > 1).sum()
)

Visits linked to more than one client: 1012

In [80]:
### Identifier Hierarchy Investigation

#The combined Digital Footprints dataset contains 120,157 unique clients, 130,236 unique visitor IDs, and 158,095 unique visit IDs.

#The expected hierarchy described in the project assumes that visitor and visit identifiers can be associated with individual clients. However, the data contains exceptions to this expected structure.

#A total of 1,645 visitor IDs are associated with more than one client ID. In addition, 1,012 visit IDs are associated with more than one client ID.

#The supplied data does not provide sufficient information to determine the cause of these relationships. They may represent shared browsing identities, identifier mapping issues, or other real world data collection behavior.

#This finding is particularly important for customer journey reconstruction because grouping events using only `visit_id` could combine events belonging to different clients.

#Therefore, the combination of `client_id` and `visit_id` will be considered as a potential session level analytical unit. This approach will be finalized before journey KPIs are calculated.

In [81]:
web_clients = set(web_df["client_id"])
experiment_clients = set(experiment_df["client_id"])

print(
    "Web clients not in experiment roster:",
    len(web_clients - experiment_clients)
)

print(
    "Experiment roster clients not in web data:",
    len(experiment_clients - web_clients)
)

Web clients not in experiment roster: 49548
Experiment roster clients not in web data: 0

In [82]:
ab_clients = set(
    experiment_df.loc[
        experiment_df["Variation"].notna(),
        "client_id"
    ]
)

print(
    "Test and Control clients:",
    len(ab_clients)
)

print(
    "Test and Control clients missing from web data:",
    len(ab_clients - web_clients)
)

Test and Control clients: 50500
Test and Control clients missing from web data: 0

In [83]:
### Experimental Client Coverage

#The Digital Footprints dataset contains 120,157 unique client IDs, which is larger than the 70,609 clients represented in the Experiment Roster and Client Profiles.

#A total of 49,548 web clients are not present in the Experiment Roster. These clients have recorded digital activity but cannot be classified as Test or Control using the supplied experiment data.

#All 70,609 clients in the Experiment Roster appear in the Digital Footprints dataset.

#More importantly, all 50,500 clients assigned to either Test or Control have recorded web activity. Therefore, there are no Test or Control clients completely missing from the Digital Footprints data.

#For direct A/B comparisons, the primary experimental population will consist of the 50,500 clients with a recorded Test or Control assignment. Web clients without a known experimental assignment will not be included in direct Test versus Control comparisons.

In [84]:
duplicate_events = web_df[
    web_df.duplicated(keep=False)
].sort_values(
    ["client_id", "visit_id", "date_time"]
)

duplicate_events.head(20)

,client_id,visitor_id,visit_id,process_step,date_time
631355,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:08
631356,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:08
631353,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:28
631354,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:28
639529,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:29:00
639530,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:29:00
639524,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:36:18
639525,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:36:18
639521,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:36:40
639522,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:36:40
639518,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:37:14
639519,2078,585735301_21309149782,900598259_99565669243_552843,start,2017-05-06 08:37:14
629801,2476,456677711_73618046413,697934864_7073193369_114100,start,2017-05-28 16:32:57
629802,2476,456677711_73618046413,697934864_7073193369_114100,start,2017-05-28 16:32:57
629799,2476,456677711_73618046413,697934864_7073193369_114100,start,2017-05-28 16:33:23
629800,2476,456677711_73618046413,697934864_7073193369_114100,start,2017-05-28 16:33:23
659998,2638,246474734_87552546214,588186957_52101970062_165660,start,2017-06-10 20:39:20
659999,2638,246474734_87552546214,588186957_52101970062_165660,start,2017-06-10 20:39:20
340965,5459,128322125_76706471522,86991584_85213257843_356594,start,2017-04-27 11:53:56
340966,5459,128322125_76706471522,86991584_85213257843_356594,start,2017-04-27 11:53:56

In [85]:
web_df.duplicated().sum()

np.int64(10764)

In [88]:
print(
    "Rows involved in exact duplicate groups:",
    len(duplicate_events)
)

print(
    "Clients affected by exact duplicates:",
    duplicate_events["client_id"].nunique()
)

Rows involved in exact duplicate groups: 19816
Clients affected by exact duplicates: 6823

In [89]:
### Duplicate Event Investigation

#The combined Digital Footprints dataset contains 10,764 additional exact duplicate records.

#Using all duplicate occurrences, including the first occurrence of each duplicated group, 19,816 rows are involved in duplicate groups across 6,823 clients.

#Inspection confirmed that these records contain identical values across `client_id`, `visitor_id`, `visit_id`, `process_step`, and `date_time`.

#Because all recorded attributes are identical, the additional copies are treated as duplicated event records rather than separate user interactions.

#Exact duplicate rows will therefore be removed before customer journey reconstruction. However, repeated process steps with different timestamps will be retained because they may represent genuine user behaviour such as restarting, repeating a step, or navigating backward.

In [91]:
### Gender Category Decision

#The `gendr` variable contains the categories `M`, `F`, `U`, and `X`, together with 14 missing values.

#The supplied metadata identifies `gendr` as the client's gender but does not define the specific meaning of `U` or `X`. Therefore, these values will not be recoded based on assumptions.

#In particular, `U` will not be changed to `Gender Neutral` because there is no evidence in the supplied documentation that `U` represents this category.

#The original gender values will be preserved to maintain the integrity of the source data. If clearer labels are required later for Tableau or the business presentation, any presentation-level grouping will be clearly documented and the original `gendr` variable will remain unchanged.

In [92]:
###removing exact web duplicates
web_clean_df = web_df.drop_duplicates().copy()

print("Original events:", len(web_df))
print("Clean events:", len(web_clean_df))
print("Removed:", len(web_df) - len(web_clean_df))
print("Remaining duplicates:", web_clean_df.duplicated().sum())

Original events: 755405
Clean events: 744641
Removed: 10764
Remaining duplicates: 0

In [95]:
####Can we trust our data enough to perform the experiment analysis?
###Multiple starts

In [96]:
#Confirm the cleaned web data
web_clean_df = web_df.drop_duplicates().copy()

print("Original events:", len(web_df))
print("Clean events:", len(web_clean_df))
print("Events removed:", len(web_df) - len(web_clean_df))
print("Remaining duplicates:", web_clean_df.duplicated().sum())

Original events: 755405
Clean events: 744641
Events removed: 10764
Remaining duplicates: 0

In [97]:
#Count starts and confirms per client session
#Purpose: This creates one row for each client session and counts how many times each process step occurred.
session_steps = (
    web_clean_df
    .groupby(["client_id", "visit_id", "process_step"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

session_steps.head()

process_step,client_id,visit_id,confirm,start,step_1,step_2,step_3
0,169,749567106_99161211863_557568,1,1,1,1,1
1,336,649044751_80905125055_554468,0,2,0,0,0
2,546,731811517_9330176838_94847,1,1,1,1,1
3,555,637149525_38041617439_716659,1,1,1,1,1
4,647,40369564_40101682850_311847,1,1,1,1,1

In [98]:
#Investigate multiple starts
multiple_starts = session_steps[
    session_steps["start"] > 1
]

print(
    "Sessions with multiple starts:",
    len(multiple_starts)
)

Sessions with multiple starts: 49873

In [99]:
multiple_starts.head(10)

process_step,client_id,visit_id,confirm,start,step_1,step_2,step_3
1,336,649044751_80905125055_554468,0,2,0,0,0
5,722,984487154_55831795985_521110,1,2,3,2,1
6,786,640294664_79662229470_499394,1,2,1,1,1
7,805,451173196_11661340552_563345,0,2,1,2,0
11,934,7076463_57954418406_971348,0,4,0,0,0
23,1346,27144337_83739845380_214282,0,5,2,1,2
26,1399,355891466_83298426087_683392,1,2,2,1,1
29,1516,481123290_95510977345_707323,0,5,3,3,0
30,1531,110350144_67985219545_904677,1,3,1,1,1
31,1543,48544987_94878616044_157787,1,2,1,1,1

In [100]:
#Investigate multiple confirms
multiple_confirms = session_steps[
    session_steps["confirm"] > 1
]

print(
    "Sessions with multiple confirms:",
    len(multiple_confirms)
)

Sessions with multiple confirms: 8248

In [101]:
multiple_confirms.head(10)

process_step,client_id,visit_id,confirm,start,step_1,step_2,step_3
22,1336,614001770_19101025926_112779,2,0,0,0,0
27,1508,673746462_59870037712_480649,5,1,1,1,1
49,1836,624455994_87386716654_950064,2,1,1,1,1
71,3891,114371834_89143120525_109144,2,0,0,0,0
73,3891,253897331_99613612893_117969,2,0,0,0,0
75,3891,620850989_47411443123_407522,3,0,0,0,0
103,5444,749998701_65314981232_187129,2,1,1,1,1
147,7856,451377635_71246219007_710032,2,1,1,1,1
164,8983,276374341_43820679967_468937,2,2,2,1,1
167,9282,428395494_37132491958_579771,2,1,1,1,1

In [102]:
#Sessions without a start
# if a session without a recorded start cannot straightforwardly be used to calculate full journey completion time.
no_start = session_steps[
    session_steps["start"] == 0
]

print(
    "Sessions without a start:",
    len(no_start)
)

Sessions without a start: 13277

In [103]:
#Sessions without a confirm
#may contain abandoned or incomplete journeys
no_confirm = session_steps[
    session_steps["confirm"] == 0
]

print(
    "Sessions without a confirm:",
    len(no_confirm)
)

Sessions without a confirm: 68474

In [104]:
### Session Event Quality Investigation

#After removing exact duplicate events, the Digital Footprints dataset contains 744,641 recorded events.

#Customer sessions were defined using the combination of `client_id` and `visit_id` because the earlier identifier investigation showed that some `visit_id` values are associated with multiple clients.

#The session-level investigation identified substantial variation in customer navigation behaviour.

#A total of 49,873 sessions contain multiple `start` events, while 8,248 sessions contain multiple `confirm` events. These events will not automatically be removed because they may represent genuine customer behaviour such as restarting, repeating actions, or navigating through the process multiple times within a session.

#There are also 13,277 sessions without a recorded `start`. These sessions cannot be used straightforwardly to calculate full journey completion time because the beginning of the journey is not observed.

#A total of 68,474 sessions contain no `confirm` event. These sessions will not be removed because they may represent incomplete or abandoned journeys, which are directly relevant to the analysis of process completion.

#The findings demonstrate that a browsing session cannot automatically be treated as a single linear customer journey. A consistent journey reconstruction methodology must therefore be established before calculating completion, duration, navigation error, and funnel KPIs.

In [105]:
#calculate the total number of client sessions.
total_sessions = len(session_steps)

print("Total client sessions:", total_sessions)

Total client sessions: 159112

In [106]:
#calculate percentages
print(
    "Multiple starts:",
    round(len(multiple_starts) / total_sessions * 100, 2),
    "%"
)

print(
    "Multiple confirms:",
    round(len(multiple_confirms) / total_sessions * 100, 2),
    "%"
)

print(
    "No start:",
    round(len(no_start) / total_sessions * 100, 2),
    "%"
)

print(
    "No confirm:",
    round(len(no_confirm) / total_sessions * 100, 2),
    "%"
)

Multiple starts: 31.34 %
Multiple confirms: 5.18 %
No start: 8.34 %
No confirm: 43.04 %

In [108]:
### Session Pattern Summary

#The cleaned Digital Footprints dataset contains 159,112 client-session combinations.

#Among these sessions, 31.34% contain more than one `start` event, while 5.18% contain multiple `confirm` events. In addition, 8.34% of sessions have no recorded `start`, and 43.04% have no recorded `confirm`.

#These categories are not mutually exclusive. A single session may belong to more than one category.

#The high frequency of multiple starts and incomplete sessions indicates that customer behaviour is often non-linear. These patterns should therefore not be treated automatically as data errors.

#Sessions without a `confirm` will be retained because incomplete journeys are directly relevant to Vanguard's completion and abandonment questions.

#Sessions without a `start` will also be retained for navigation analysis, although they cannot be used straightforwardly for full start-to-confirm completion time calculations.

#These findings confirm that customer journeys must be reconstructed carefully before business KPIs are calculated.

In [110]:
###backward navigation
#to check whether clients experience fewer navigation errors.
step_order = {
    "start": 0,
    "step_1": 1,
    "step_2": 2,
    "step_3": 3,
    "confirm": 4
}
web_clean_df["step_number"] = (
    web_clean_df["process_step"]
    .map(step_order)
)
web_clean_df = web_clean_df.sort_values(
    ["client_id", "visit_id", "date_time"]
)
web_clean_df["previous_step"] = (
    web_clean_df
    .groupby(["client_id", "visit_id"])["step_number"]
    .shift(1)
)
web_clean_df["backward_navigation"] = (
    web_clean_df["step_number"]
    < web_clean_df["previous_step"]
)

print(
    "Backward navigation events:",
    web_clean_df["backward_navigation"].sum()
)

Backward navigation events: 62880

In [111]:
#62,880 backward navigation events after exact duplicates were removed.
#does not mean 62,880 clients made errors. One client can generate several backward events, and one session can contain several.

In [112]:
#How many sessions experienced backward navigation?

In [113]:
sessions_with_backward = (
    web_clean_df
    .groupby(["client_id", "visit_id"])["backward_navigation"]
    .any()
    .sum()
)

print(
    "Sessions with backward navigation:",
    sessions_with_backward
)

print(
    "Percentage of sessions with backward navigation:",
    round(sessions_with_backward / total_sessions * 100, 2),
    "%"
)

Sessions with backward navigation: 39949
Percentage of sessions with backward navigation: 25.11 %

In [114]:
#Which backward movements occur most often? to reveal where customers struggle.

This can reveal where customers struggle.

backward_events = web_clean_df[
    web_clean_df["backward_navigation"] == True
].copy()

backward_events["previous_process_step"] = (
    backward_events["previous_step"]
    .map({
        0: "start",
        1: "step_1",
        2: "step_2",
        3: "step_3",
        4: "confirm"
    })
)

backward_events[
    ["previous_process_step", "process_step"]
].value_counts()

previous_process_step  process_step
step_1                 start           23587
step_2                 step_1          12171
step_3                 step_2           9418
                       start            8265
step_2                 start            5940
step_3                 step_1           1637
confirm                start            1109
                       step_1            552
                       step_3            194
                       step_2              7
Name: count, dtype: int64

In [115]:
### Backward Navigation Findings

#A total of 62,880 backward navigation events were identified across 39,949 client sessions after exact duplicate events were removed.

#This means that 25.11% of the 159,112 client sessions experienced at least one backward movement.

#The most common backward transition was `step_1` to `start`, with 23,587 occurrences. Other frequent backward transitions included `step_2` to `step_1` with 12,171 occurrences, `step_3` to `step_2` with 9,418 occurrences, and `step_3` to `start` with 8,265 occurrences.

#Backward navigation is not automatically classified as an error because customers may legitimately return to previous steps to review or correct information. However, its frequency provides an important indicator of potential navigation friction.

#The Test and Control groups will later be compared to determine whether the redesigned interface reduced backward navigation and whether particular process steps remain potential bottlenecks.

In [116]:
#DATA INTEGRITY TEST
#Tenure years versus tenure months
demo_df["tenure_years_from_months"] = (
    demo_df["clnt_tenure_mnth"] / 12
)

demo_df[
    [
        "clnt_tenure_yr",
        "clnt_tenure_mnth",
        "tenure_years_from_months"
    ]
].head(10)

   clnt_tenure_yr  clnt_tenure_mnth  tenure_years_from_months
0             6.0              73.0                  6.083333
1             7.0              94.0                  7.833333
2             5.0              64.0                  5.333333
3            16.0             198.0                 16.500000
4            12.0             145.0                 12.083333
5             5.0              71.0                  5.916667
6             5.0              66.0                  5.500000
7            30.0             361.0                 30.083333
8            30.0             369.0                 30.750000
9            15.0             189.0                 15.750000

In [117]:
demo_df["tenure_difference"] = (
    demo_df["clnt_tenure_yr"]
    - demo_df["tenure_years_from_months"]
).abs()

demo_df["tenure_difference"].describe()

count    70595.000000
mean         0.501997
std          0.317867
min          0.000000
25%          0.166667
50%          0.500000
75%          0.833333
max          1.000000
Name: tenure_difference, dtype: float64

In [118]:
demo_df.nlargest(
    10,
    "tenure_difference"
)[
    [
        "client_id",
        "clnt_tenure_yr",
        "clnt_tenure_mnth",
        "tenure_years_from_months",
        "tenure_difference"
    ]
]

,client_id,clnt_tenure_yr,clnt_tenure_mnth,tenure_years_from_months,tenure_difference
113,7045562,7.0,96.0,8.0,1.0
1035,6895833,7.0,96.0,8.0,1.0
1529,6915261,11.0,144.0,12.0,1.0
1648,911208,11.0,144.0,12.0,1.0
1703,346409,15.0,192.0,16.0,1.0
2196,3071537,3.0,48.0,4.0,1.0
12235,1114136,15.0,192.0,16.0,1.0
13343,7041735,11.0,144.0,12.0,1.0
16310,7479669,23.0,288.0,24.0,1.0
23813,2798244,7.0,96.0,8.0,1.0

In [120]:
#Do our demographic issues affect Test and Control?
#Missing demographic records
missing_demo_clients = demo_df[
    demo_df.isnull().any(axis=1)
][["client_id"]]
missing_demo_variation = missing_demo_clients.merge(
    experiment_df,
    on="client_id",
    how="left"
)

missing_demo_variation["Variation"].value_counts(
    dropna=False
)

Variation
Test       7
Control    6
NaN        2
Name: count, dtype: int64

In [121]:
#Age versus tenure inconsistencies
age_tenure_issue
age_tenure_variation = age_tenure_issue[
    ["client_id"]
].merge(
    experiment_df,
    on="client_id",
    how="left"
)

age_tenure_variation["Variation"].value_counts(
    dropna=False
)
age_tenure_variation["Variation"].value_counts(
    dropna=False,
    normalize=True
) * 100

Variation
NaN        42.334495
Test       32.404181
Control    25.261324
Name: proportion, dtype: float64

In [ ]:
##Conclusion: Can We Trust the Data?

#The initial data quality assessment identified several real world data challenges, but no issue was found that prevents the Vanguard A/B experiment from being analyzed.

#The Client Profiles and Experiment Roster contain the same 70,609 unique clients, and all 50,500 clients assigned to Test or Control have recorded web activity.

#Missing demographic information is limited to 15 clients. Several demographic anomalies were identified, including 574 clients whose recorded tenure exceeds their age. These records were retained because the available data does not establish which value is incorrect.

#Client balances are strongly right skewed, with 11.36% classified as IQR outliers. These observations were retained because high investment balances may represent legitimate Vanguard clients rather than data errors.

#The Digital Footprints dataset initially contained 755,405 events. A total of 10,764 exact duplicate event records were removed, resulting in 744,641 events for subsequent journey analysis.

#Customer navigation is frequently non linear. Multiple starts, multiple confirms, sessions without starts, sessions without confirms, and backward navigation were observed. These patterns were retained because they may represent genuine customer behaviour and are relevant to Vanguard's customer experience questions.

#Some visitor and visit identifiers are associated with multiple clients. Therefore, `client_id` and `visit_id` together will be used when analyzing client sessions rather than relying on `visit_id` alone.

#For direct A/B comparisons, analysis will be restricted to clients with a known Test or Control assignment.

#Overall, the data is suitable for further analysis provided that the identified limitations and methodological decisions are consistently applied and documented.